version: '3.7'

x-common-variables: &common
  NODE_ENV: production
  DB_HOST: database
  DB_CLIENT: pg

networks:
  postgres_database:

secrets:
  ADMIN_DB_USER:
    external: true
  ADMIN_DB_PASS:
    external: true
  PINNY_TOKEN:
    external: true

services:
  database:
    image: postgres
    deploy:
      replicas: 1
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 256M
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      -
        type: bind
        source: ~/docker/volumes/postgres
        target: /usr/lib/postgresql/data
    secrets:
      - ADMIN_DB_USER
      - ADMIN_DB_PASS
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/ADMIN_DB_PASS
      POSTGRES_USER_FILE: /run/secrets/ADMIN_DB_USER
    ports:
      - 5432:5432
    networks:
      - postgres_database
  pinny:
    image: imstonic/pinny
    deploy:
      replicas: 1
    environment:
      <<: *common
      DB_NAME: postgres
    secrets:
      - ADMIN_DB_USER
      - ADMIN_DB_PASS
      - PINNY_TOKEN
    depends_on:
      - database
    networks:
      - postgres_database
